name: randchoice
description: A micro library for picking random item(s) from lists.
version: 0.0.1
homepage: https://github.com/daftspaniel/randchoice
author: Davy Mitchell <daftspaniel@gmail.com>

environment:
  sdk: '>=1.24.2 <2.0.0-dev.infinity'

dev_dependencies:
  test: ^0.12.0
